/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as LoginsRouteImport } from './routes/logins'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyWisdomIndexRouteImport } from './routes/daily-wisdom.index'
import { Route as DailyWisdomSlugRouteImport } from './routes/daily-wisdom.$slug'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginsRoute = LoginsRouteImport.update({
  id: '/logins',
  path: '/logins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyWisdomIndexRoute = DailyWisdomIndexRouteImport.update({
  id: '/daily-wisdom/',
  path: '/daily-wisdom/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyWisdomSlugRoute = DailyWisdomSlugRouteImport.update({
  id: '/daily-wisdom/$slug',
  path: '/daily-wisdom/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logins': typeof LoginsRoute
  '/phases': typeof PhasesRoute
  '/schedule': typeof ScheduleRoute
  '/students': typeof StudentsRoute
  '/today': typeof TodayRoute
  '/daily-wisdom/$slug': typeof DailyWisdomSlugRoute
  '/daily-wisdom/': typeof DailyWisdomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logins': typeof LoginsRoute
  '/phases': typeof PhasesRoute
  '/schedule': typeof ScheduleRoute
  '/students': typeof StudentsRoute
  '/today': typeof TodayRoute
  '/daily-wisdom/$slug': typeof DailyWisdomSlugRoute
  '/daily-wisdom': typeof DailyWisdomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logins': typeof LoginsRoute
  '/phases': typeof PhasesRoute
  '/schedule': typeof ScheduleRoute
  '/students': typeof StudentsRoute
  '/today': typeof TodayRoute
  '/daily-wisdom/$slug': typeof DailyWisdomSlugRoute
  '/daily-wisdom/': typeof DailyWisdomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logins'
    | '/phases'
    | '/schedule'
    | '/students'
    | '/today'
    | '/daily-wisdom/$slug'
    | '/daily-wisdom/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logins'
    | '/phases'
    | '/schedule'
    | '/students'
    | '/today'
    | '/daily-wisdom/$slug'
    | '/daily-wisdom'
  id:
    | '__root__'
    | '/'
    | '/logins'
    | '/phases'
    | '/schedule'
    | '/students'
    | '/today'
    | '/daily-wisdom/$slug'
    | '/daily-wisdom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginsRoute: typeof LoginsRoute
  PhasesRoute: typeof PhasesRoute
  ScheduleRoute: typeof ScheduleRoute
  StudentsRoute: typeof StudentsRoute
  TodayRoute: typeof TodayRoute
  DailyWisdomSlugRoute: typeof DailyWisdomSlugRoute
  DailyWisdomIndexRoute: typeof DailyWisdomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logins': {
      id: '/logins'
      path: '/logins'
      fullPath: '/logins'
      preLoaderRoute: typeof LoginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-wisdom/': {
      id: '/daily-wisdom/'
      path: '/daily-wisdom'
      fullPath: '/daily-wisdom/'
      preLoaderRoute: typeof DailyWisdomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-wisdom/$slug': {
      id: '/daily-wisdom/$slug'
      path: '/daily-wisdom/$slug'
      fullPath: '/daily-wisdom/$slug'
      preLoaderRoute: typeof DailyWisdomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginsRoute: LoginsRoute,
  PhasesRoute: PhasesRoute,
  ScheduleRoute: ScheduleRoute,
  StudentsRoute: StudentsRoute,
  TodayRoute: TodayRoute,
  DailyWisdomSlugRoute: DailyWisdomSlugRoute,
  DailyWisdomIndexRoute: DailyWisdomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
